version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: psw123
      - MYSQL_DATABASE: db
  node:
    image: node:22
    environment:
      - NODE_ENV=production
      -
    volumes:
      -
    expose:
      - 80
    ports:
      - '80:80'
